name: fingerprint
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.1.6
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.3
  shared_preferences: ^2.0.20
  fluttertoast: ^8.2.1
  url_launcher: ^6.1.10
  google_fonts: ^4.0.3
  lottie: ^2.3.2
  intl: ^0.17.0
  awesome_dialog: ^3.0.2
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.5.3
  firebase_database: ^10.1.1
  camera: ^0.9.4+5
  device_info_plus:
  http:
  firebase_storage: ^11.2.1
  image_picker:
  cached_network_image:




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/image/logoicon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/donations/
    - assets/imagejson/

